#! /bin/bash

sudo docker run -v $HOME/yts/ipython/notebooks:/notebooks -v $HOME/yts/ipython/logfile:/logfile -v $HOME/yts/ipython/www:/var/www/html -p 8880:80 -p 8888:8888 -d ipython-notebook-runipy
